[package]
name = "eldlib-rs"
version = "0.1.0"
authors = ["jean-pierre both <jeanpierre.both@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[build-dependencies]
bindgen = "0.20.0"

[package]
build = "build.rs"